name: py36

# python 3.6
channels:
  - conda-forge

dependencies:
  - openssl
  - pip
  - setuptools
  - python=3.6.1
  - pynacl
  - wheel
  - zlib
  - libffi
  # requirements for rtd
  - pip:
    - git+https://github.com/sphinx-doc/sphinx
    - sphinx-autodoc-typehints
    - sphinxcontrib-asyncio
    - sphinx_py3doc_enhanced_theme
    - curio
    - pylru
    - asks
    - pytz
    - oauthlib
    - multidict
    - yarl
    - wsproto
    - multio
    - asyncwebsockets